[workspace]
members = ["rust/*", "mixed/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
description = "Rust code"
authors = ["Krystian Krakowski <kkrakowski22@gmail.com>"]
readme = "README.md"
rust-version = "1.78"
